spring:
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  sleuth:
    sampler:
      percentage: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/asset_risk?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&&useOldAliasMetadataBehavior=true
    username: root
    password: 123456
  # Redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
    timeout: 5000
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
    #这个配置是保证提供者确保消息推送到交换机中，不管成不成功，都会回调
    publisher-confirm-type: correlated
    #保证交换机能把消息推送到队列中
    publisher-returns: true
    virtual-host: /
    #这个配置是保证消费者会消费消息，手动确认
    listener:
      simple:
        acknowledge-mode: manual
    template:
      mandatory: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000

# mqtt配置
mqtt-setting:
  exchange: amp.topic
  export-route-key: key.export
  export-pub-topic: exportData
  concurrent_consumers: 1
  maxConcurrent_consumers: 1
  prefetch_count: 1

my-config:
  minio:
    endpoint: http://49.235.104.19:9000
    accesskey: minioadmin
    secretkey: minioadmin
  upload:
    defFolder: def
    defBucket: assertfiles