spring:
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  sleuth:
    sampler:
      percentage: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/asset_risk_test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&&useOldAliasMetadataBehavior=true&rewriteBatchedStatements=true
    username: root
    password: 123456
  # Redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    pool:
      max-idle: 1000
      min-idle: 0
      max-active: 1000
      max-wait: -1
    timeout: 5000
  #flyway
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: schema
    #baseline-version: 1 #低于该版本号的sql全部禁用 - 测试使用
    out-of-order: false #对于开发环境, 可能是多人协作开发, 很可能先 apply 了自己本地的最新 SQL 代码, 然后发现其他同事早先时候提交的 SQL 代码还没有 apply, 所以 开发环境应该设置 spring.flyway.outOfOrder=true, 这样 flyway 将能加载漏掉的老版本 SQL 文件; 而生产环境应该设置 spring.flyway.outOfOrder=false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

server-setting:
  is_prod: 0
  host_name: 49.235.104.19
  user_name: root
  pwd: Lhh110112
  exec_timeout: 60

mqtt-setting:
  # mqtt服务器broker
  host: localhost
  port: 5672
  userName: guest
  password: guest
  concurrent_consumers: 1
  maxConcurrent_consumers: 10
  prefetch_count: 1
