spring:
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  sleuth:
    sampler:
      percentage: 1
  # Redis 配置
  redis:
    host: localhost
    port: 6379
    password: 123456
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
    timeout: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000

# mqtt配置
mqtt-setting:
  # mqtt服务器broker
  host: 49.235.104.19
  port: 5672
  userName: admin
  password: 123456
  pub-topic: projectData
  concurrent_consumers: 1
  maxConcurrent_consumers: 10
  prefetch_count: 1
  sub-num: 2